(add-to-list 'load-path "~/.emacs.d/vendor")

(setq custom-file "~/.emacs.d/lisp/rmm5t/custom.el")
(load custom-file 'noerror)

(load "rmm5t/jaequery")
(load "rmm5t/tabbar")
(load "rmm5t/theme")
(load "rmm5t/env")
(load "rmm5t/global")
(load "rmm5t/defuns")
;(load "rmm5t/bindings")
;(load "rmm5t/kbd-macros")
(load "rmm5t/tabs")
(load "rmm5t/disabled")
(load "rmm5t/fonts")
(load "rmm5t/utf-8")
(load "rmm5t/scratch")
(load "rmm5t/grep")
(load "rmm5t/diff")
(load "rmm5t/ido") ; currently configured with flx instead
(load "rmm5t/dired")
(load "rmm5t/recentf")
(load "rmm5t/rectangle")
(load "rmm5t/org")
(load "rmm5t/zoom")
(load "rmm5t/flymake")
(load "rmm5t/javascript")
(load "rmm5t/ri-emacs")
(load "rmm5t/mac")
;(load "rmm5t/server")
;(load "rmm5t/server-mode")
(load "rmm5t/shell-mode")
(load "rmm5t/ruby-mode")
(load "rmm5t/saveplace")
(load "rmm5t/private" 'noerror)

;; (load "rmm5t/hl-line")
;; (load "rmm5t/iswitchb")

;; (vendor 'flx)
;(vendor 'expand-region 'er/expand-region)
;(vendor 'multiple-cursors 'mc/edit-lines 'mc/mark-next-like-this 'mc/mark-previous-like-this 'mc/mark-all-like-this 'set-rectangular-region-anchor)
;(vendor 'jump-char     'jump-char-forward 'jump-char-backward)
;(vendor 'rinari)
;(vendor 'textmate)
;(vendor 'maxframe      'mf 'maximize-frame)
;(vendor 'filladapt)
;(vendor 'coffee-mode)
;(vendor 'haml-mode)
;(vendor 'sass-mode)
;(vendor 'htmlize)
;; (vendor 'ruby-electric 'ruby-electric-mode)
;; (vendor 'auctex)
